# Generated by Django 5.0.3 on 2024-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_recruiter_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(max_length=100),
        ),
    ]
